# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Push docker Dev image

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build Maven and package as JAR
        run: mvn -B package -DskipTests --file pom.xml

      - name: Build and Push docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: renatgatin/todoapp-api-docker
          tag: develop
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
