name: Test, Build and Deploy to Amazon ECS Develop

on:
  push:
    branches:
      - develop

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run test-build-deploy-aws template workflow
        uses: ./.github/workflows/templates/test-build-deploy-workflow
        with:
          branch: dev
          environment: develop
