name: Test, Build and Deploy to Amazon ECS Develop

on:
  push:
    branches:
      - develop

jobs:
  test-build-deploy:
    name: Run test-build-deploy-aws template workflow
    uses: RenatGatin/todoapp-api/.github/workflows/test-build-deploy-workflow.yml@master
    with:
      branch: dev
      environment: develop
