# Reusable workflow for test
############   MERGE ALWAYS TO MASTER  #############

name: Test

on:
  workflow_call:
    inputs:
      branch:
        description: develop | release | master
        required: true
        type: string

jobs:
  test:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: ${{inputs.branch}}
          GITHUB_TOKEN: 08b0197995350fb65c4ee4920bec50cbc30d38ca
